/**
 * @file configs.hpp
 * @author Paul Bucamp
 * @brief Values mapping used for the fingerprint generation
 * @version 1.0
 * @date 2022-03-03
 */
#ifndef FINGER_CONFIGS_HPP
#define FINGER_CONFIGS_HPP

#include <map>
#include <string>
#include <vector>

/**
 * @brief HTTP Request field "Accept-Encoding" values
 */
static const std::map<std::string, std::string> AE = {
    { "gzip", "gz" },     { "deflate", "de" }, { "identity", "id" },
    { "none", "no" },     { "sdch", "sd" },    { "br", "br" },
    { "compress", "co" }, { "*", "as" },       { "chunked", "ch" },
};

/**
 * @brief HTTP Request field "Connection" values
 */
static const std::map<std::string, std::string> CONN = {
    { "Keep-Alive", "Ke-Al" }, { "keep-alive", "ke-al" }, { "close", "cl" },
    { "Close", "Cl" },         { "Upgrade", "Up" },
};

/**
 * @brief HTTP Request field "Content-Encoding" values
 */
static const std::map<std::string, std::string> CONTENC = {
    { "gzip", "gz" }, { "deflate", "de" },  { "identity", "id" }, { "binary", "bi" },
    { "br", "bt" },   { "compress", "co" }, { "UTF8", "UT" },
};

/**
 * @brief HTTP Request field "Cache-Control" values
 */
static const std::map<std::string, std::string> CACHECONT = {
    { "max-age", "ma" },      { "no-cache", "nc" },        { "no-store", "ns" },
    { "no-transform", "nt" }, { "only-if-cached", "oic" },
};

/**
 * @brief HTTP Request field "TE" values
 */
static const std::map<std::string, std::string> TE = {
    { "gzip", "gz" }, { "deflate", "de" },  { "compress", "co" },
    { "http", "ht" }, { "trailers", "tr" },
};

/**
 * @brief HTTP Request field "Accept-Charset" values
 */
static const std::map<std::string, std::string> ACCPTCHAR = { { "windows-1251", "w1" },
                                                              { "utf-8", "ut" },
                                                              { "*", "as" },
                                                              { "iso-8859-1", "is" } };

static const std::vector<std::map<int, std::string>> FEATURESET = {
    {
    { 1, "s" },
    { 2, "i" },
    { 3, "s" },
    { 6, "f" },
    { 9, "s" },
    { 10, "s" },
    { 13, "f" },
    },
    {
    { 0, "i" },
    { 1, "s" },
    { 2, "i" },
    { 3, "s" },
    { 4, "i" },
    { 5, "s" },
    { 6, "i" },
    { 7, "s" },
    { 8, "s" },
    { 9, "s" },
    { 10, "s" },
    { 11, "s" },
    { 12, "i" },
    { 13, "i" },
    },
    {
    { 0, "i" },
    { 1, "s" },
    { 2, "i" },
    { 3, "s" },
    { 6, "f" },
    { 7, "s" },
    { 8, "s" },
    { 9, "s" },
    { 10, "s" },
    { 11, "s" },
    { 12, "i" },
    { 13, "f" },
    },
    {
    { 0, "i" },
    { 2, "i" },
    { 3, "s" },
    { 6, "i" },
    { 9, "s" },
    },
    {
    { 0, "f" },
    { 1, "s" },
    { 2, "f" },
    { 3, "s" },
    { 4, "f" },
    { 6, "f" },
    { 7, "s" },
    { 8, "s" },
    { 9, "s" },
    { 10, "s" },
    { 11, "s" },
    { 12, "f" },
    { 13, "f" },
    },
};

/**
 * @brief HTTP Request field "Method" values
 */
static const std::vector<std::string> METHODS = {
    "GET", "POST", "HEAD", "PUT", "DELETE", "CONNECT", "OPTIONS", "TRACE", "PATCH",
};

static std::map<std::string, std::string> HDRL = {
    { "accept", "ac" },
    { "accept-charset", "ac-ch" },
    { "accept-datetime", "ac-da" },
    { "accept-encoding", "ac-en" },
    { "accept-language", "ac-la" },
    { "access-control-request-headers", "a-c-r-h" },
    { "access-control-request-method", "a-c-r-m" },
    { "a-im", "a-i" },
    { "authorization", "au" },
    { "cache-control", "ca-co" },
    { "connection", "co" },
    { "content-length", "co-le" },
    { "content-type", "co-ty" },
    { "content-encoding", "co-en" },
    { "cookie", "ck" },
    { "date", "da" },
    { "dnt", "dn" },
    { "expect", "ex" },
    { "forwarded", "fo" },
    { "from", "fr" },
    { "front-end-https", "f-e-h" },
    { "host", "ho" },
    { "http2-settings", "ht-se" },
    { "if-match", "if-ma" },
    { "if-modified-since", "i-m-s" },
    { "if-none-match", "i-n-m" },
    { "if-range", "if-ra" },
    { "if-unmodified-since", "i-u-s" },
    { "keep-alive", "ke-al" },
    { "max-forwards", "ma-fo" },
    { "origin", "or" },
    { "pragma", "pr" },
    { "proxy-authorization", "pr-au" },
    { "proxy-connection", "pr-co" },
    { "range", "ra" },
    { "referer", "re" },
    { "save-data", "sa-da" },
    { "te", "te" },
    { "upgrade", "up" },
    { "upgrade-insecure-requests", "u-i-r" },
    { "user-agent", "us-ag" },
    { "via", "vi" },
    { "warning", "wa" },
    { "x-att-deviceid", "x-a-d" },
    { "x-correlation-id", "x-c-i" },
    { "x-csrf-token", "x-c-t" },
    { "x-forwarded-for", "x-f-f" },
    { "x-forwarded-host", "x-f-h" },
    { "x-forwarded-proto", "x-f-p" },
    { "x-http-method-override", "x-h-m-o" },
    { "x-requested-with", "x-r-w" },
    { "x-request-id", "x-r-i" }
};

static std::map<std::string, std::string> ACCPT = {
    { "*", "as" },
    { "*/*", "as-as" },
    { "application/*", "ap-as" },
    { "application/ecmascript", "ap-ec" },
    { "application/font-woff", "ap-f-w" },
    { "application/font-woff2", "ap-f-w-2" },
    { "application/javascript", "ap-ja" },
    { "application/json", "ap-js" },
    { "application/msword", "ap-m-w" },
    { "application/octet-stream", "ap-o-s" },
    { "application/vnd.ms-excel", "ap-m-e" },
    { "application/vnd.ms-powerpoint", "ap-m-p" },
    { "application/xaml+xml", "ap-xa-xm" },
    { "application/x-ecmascript", "ap-x-e" },
    { "application/xhtml+xml", "ap-xh+xm" },
    { "application/xml", "ap-xm" },
    { "application/x-ms-application", "ap-x-m-ap" },
    { "application/x-ms-xbap", "ap-x-m-xb" },
    { "application/x-shockwave-flash", "ap-x-sh-fl" },
    { "audio/*", "au-as" },
    { "image/*", "im-as" },
    { "image/gif", "im-gi" },
    { "image/jpeg", "im-jp" },
    { "image/pjpeg", "im-pj" },
    { "image/png", "im-pn" },
    { "image/svg+xml", "im-sv-xm" },
    { "image/webp", "im-we" },
    { "image/x-xbitmap", "im-x-xb" },
    { "text/*", "te-as" },
    { "text/css", "te-cs" },
    { "text/html", "te-ht" },
    { "text/javascript", "te-ja" },
    { "text/plain", "te-pl" },
    { "text/xml", "te-xm" },
    { "video/*", "vi-as" }
};

static std::map<std::string, std::string> CONTENTTYPE = {
    { "application/javascript", "ap-ja" },
    { "application/json", "ap-js" },
    { "application/octet-stream", "ap-os" },
    { "application/pdf", "ap-pd" },
    { "application/vnd.mozilla.metrics.bz2", "ap-bz" },
    { "application/xml", "ap-xm" },
    { "application/x-octet-stream", "ap-x-o-s" },
    { "application/x-www-form-urlencoded", "ap-x-w-f-u" },
    { "audio/mpeg", "au-mp" },
    { "binary", "bi" },
    { "image/gif", "im-gi" },
    { "image/jpeg", "im-jp" },
    { "image/png", "im-pn" },
    { "message/rfc822", "me-rf" },
    { "model/mesh", "mo-me" },
    { "multipart/form-data", "mu-f-d" },
    { "octet/binary", "oc-bi" },
    { "octet-stream", "oc-st" },
    { "text/csv", "te-cs" },
    { "text/html", "te-ht" },
    { "text/plain", "te-pl" },
    { "text/xml", "te-xm" },
    { "video/h264", "vi-h2" },
    { "video/mpeg", "vi-mp" }
};

static std::vector<std::string> EXT = {
    "123",
    "1km",
    "3dm",
    "3dml",
    "3ds",
    "3g2",
    "3gp",
    "3gpp",
    "3mf",
    "7z",
    "a",
    "aab",
    "aac",
    "aam",
    "aas",
    "abw",
    "ac",
    "acc",
    "ace",
    "acu",
    "acutc",
    "ada",
    "adb",
    "adp",
    "ads",
    "aep",
    "afm",
    "afp",
    "ahead",
    "ai",
    "aif",
    "aifc",
    "aiff",
    "air",
    "ait",
    "alz",
    "ami",
    "ape",
    "apk",
    "apng",
    "appcache",
    "applescript",
    "application",
    "apr",
    "ar",
    "arc",
    "arj",
    "as",
    "asc",
    "ascii",
    "ascx",
    "asf",
    "asm",
    "asmx",
    "aso",
    "asp",
    "aspx",
    "asx",
    "atc",
    "atom",
    "atomcat",
    "atomdeleted",
    "atomsvc",
    "atx",
    "au",
    "au3",
    "avi",
    "aw",
    "awk",
    "azf",
    "azs",
    "azv",
    "azw",
    "bak",
    "baml",
    "bas",
    "bash",
    "bashrc",
    "bat",
    "bbcolors",
    "bcp",
    "bcpio",
    "bdf",
    "bdm",
    "bdoc",
    "bdsgroup",
    "bdsproj",
    "bed",
    "bh",
    "bh2",
    "bib",
    "bin",
    "bk",
    "blb",
    "blorb",
    "bmi",
    "bmml",
    "bmp",
    "book",
    "bowerrc",
    "box",
    "boz",
    "bpk",
    "bsp",
    "btif",
    "buffer",
    "bz",
    "bz2",
    "bzip2",
    "c",
    "c11amc",
    "c11amz",
    "c4d",
    "c4f",
    "c4g",
    "c4p",
    "c4u",
    "cab",
    "caf",
    "cap",
    "car",
    "cat",
    "cb7",
    "cba",
    "cbl",
    "cbr",
    "cbt",
    "cbz",
    "cc",
    "cco",
    "cct",
    "ccxml",
    "cdbcmsg",
    "cdf",
    "cdfx",
    "cdkey",
    "cdmia",
    "cdmic",
    "cdmid",
    "cdmio",
    "cdmiq",
    "cdx",
    "cdxml",
    "cdy",
    "cer",
    "cfc",
    "cfg",
    "cfm",
    "cfml",
    "cfs",
    "cgi",
    "cgm",
    "chat",
    "chm",
    "chrt",
    "cif",
    "cii",
    "cil",
    "cla",
    "class",
    "clj",
    "cljs",
    "clkk",
    "clkp",
    "clkt",
    "clkw",
    "clkx",
    "clp",
    "cls",
    "cmake",
    "cmc",
    "cmd",
    "cmdf",
    "cml",
    "cmp",
    "cmx",
    "cnf",
    "cob",
    "cod",
    "code-snippets",
    "coffee",
    "coffeekup",
    "com",
    "conf",
    "cp",
    "cpio",
    "cpp",
    "cpt",
    "cpy",
    "cr2",
    "crd",
    "crl",
    "crt",
    "crx",
    "cryptonote",
    "cs",
    "csh",
    "csl",
    "csml",
    "cson",
    "csp",
    "csproj",
    "csr",
    "css",
    "csslintrc",
    "cst",
    "csv",
    "ctl",
    "cu",
    "cur",
    "curl",
    "curlrc",
    "cww",
    "cxt",
    "cxx",
    "d",
    "dae",
    "daf",
    "dart",
    "dat",
    "dataless",
    "davmount",
    "dbk",
    "dcm",
    "dcr",
    "dcurl",
    "dd2",
    "ddd",
    "ddf",
    "dds",
    "deb",
    "def",
    "deploy",
    "der",
    "dex",
    "dfac",
    "dfm",
    "dgc",
    "dic",
    "diff",
    "dir",
    "dis",
    "dist",
    "distz",
    "djv",
    "djvu",
    "dll",
    "dmg",
    "dmp",
    "dms",
    "dna",
    "dng",
    "doc",
    "docm",
    "docx",
    "dof",
    "dot",
    "dotm",
    "dotx",
    "dp",
    "dpg",
    "dpk",
    "dpr",
    "dproj",
    "dra",
    "drle",
    "dsc",
    "dsk",
    "dssc",
    "DS_Store",
    "dtb",
    "dtd",
    "dts",
    "dtshd",
    "dump",
    "dvb",
    "dvi",
    "dwd",
    "dwf",
    "dwg",
    "dxf",
    "dxp",
    "dxr",
    "ear",
    "ecelp4800",
    "ecelp7470",
    "ecelp9600",
    "ecma",
    "eco",
    "editorconfig",
    "edm",
    "edx",
    "efif",
    "egg",
    "ei6",
    "ejs",
    "el",
    "elc",
    "elm",
    "emacs",
    "emf",
    "eml",
    "emma",
    "emotionml",
    "emz",
    "ent",
    "eol",
    "eot",
    "eps",
    "epub",
    "erb",
    "erl",
    "es",
    "es3",
    "esa",
    "esf",
    "eslintignore",
    "eslintrc",
    "et3",
    "etx",
    "eva",
    "evy",
    "ex",
    "exe",
    "exi",
    "exr",
    "exs",
    "ext",
    "ez",
    "ez2",
    "ez3",
    "f",
    "f03",
    "f4v",
    "f77",
    "f90",
    "f95",
    "fbs",
    "fcdt",
    "fcs",
    "fdf",
    "fdt",
    "fe_launch",
    "fg5",
    "fgd",
    "fh",
    "fh4",
    "fh5",
    "fh7",
    "fhc",
    "fig",
    "fish",
    "fits",
    "fla",
    "flac",
    "fli",
    "flo",
    "flv",
    "flw",
    "flx",
    "fly",
    "fm",
    "fnc",
    "fo",
    "for",
    "fpp",
    "fpx",
    "frame",
    "frm",
    "fs",
    "fsc",
    "fsproj",
    "fst",
    "fsx",
    "ftc",
    "fti",
    "ftn",
    "fvt",
    "fxp",
    "fxpl",
    "fzs",
    "g2w",
    "g3",
    "g3w",
    "gac",
    "gam",
    "gbr",
    "gca",
    "gdl",
    "gdoc",
    "gemrc",
    "gemspec",
    "geo",
    "geojson",
    "gex",
    "ggb",
    "ggt",
    "gh",
    "ghf",
    "gif",
    "gim",
    "gitattributes",
    "gitconfig",
    "gitignore",
    "gitkeep",
    "gitmodules",
    "glb",
    "gltf",
    "gml",
    "gmx",
    "gnumeric",
    "go",
    "gph",
    "gpp",
    "gpx",
    "gqf",
    "gqs",
    "gradle",
    "graffle",
    "gram",
    "gramps",
    "gre",
    "groovy",
    "groupproj",
    "grunit",
    "grv",
    "grxml",
    "gsf",
    "gsheet",
    "gslides",
    "gtar",
    "gtm",
    "gtmpl",
    "gtw",
    "gv",
    "gvimrc",
    "gxf",
    "gxt",
    "gz",
    "gzip",
    "h",
    "h261",
    "h263",
    "h264",
    "hal",
    "haml",
    "hbci",
    "hbs",
    "hdd",
    "hdf",
    "heic",
    "heics",
    "heif",
    "heifs",
    "hej2",
    "held",
    "hgignore",
    "hh",
    "hjson",
    "hlp",
    "hpgl",
    "hpid",
    "hpp",
    "hps",
    "hqx",
    "hrl",
    "hs",
    "hsj2",
    "hta",
    "htaccess",
    "htc",
    "htke",
    "htm",
    "html",
    "htpasswd",
    "hvd",
    "hvp",
    "hvs",
    "hxx",
    "i2g",
    "icc",
    "ice",
    "iced",
    "icm",
    "icns",
    "ico",
    "ics",
    "ief",
    "ifb",
    "ifm",
    "iges",
    "igl",
    "igm",
    "igs",
    "igx",
    "iif",
    "img",
    "iml",
    "imp",
    "ims",
    "in",
    "inc",
    "ini",
    "ink",
    "inkml",
    "ino",
    "install",
    "int",
    "iota",
    "ipa",
    "ipfix",
    "ipk",
    "irbrc",
    "irm",
    "irp",
    "iso",
    "itcl",
    "itermcolors",
    "itk",
    "itp",
    "its",
    "ivp",
    "ivu",
    "jad",
    "jade",
    "jam",
    "jar",
    "jardiff",
    "java",
    "jhc",
    "jhtm",
    "jhtml",
    "jisp",
    "jls",
    "jlt",
    "jng",
    "jnlp",
    "joda",
    "jp2",
    "jpe",
    "jpeg",
    "jpf",
    "jpg",
    "jpg2",
    "jpgm",
    "jpgv",
    "jph",
    "jpm",
    "jpx",
    "js",
    "jscsrc",
    "jse",
    "jshintignore",
    "jshintrc",
    "json",
    "json5",
    "jsonld",
    "jsonml",
    "jsp",
    "jspx",
    "jsx",
    "jxr",
    "jxra",
    "jxrs",
    "jxs",
    "jxsc",
    "jxsi",
    "jxss",
    "kar",
    "karbon",
    "kdbx",
    "key",
    "keynote",
    "kfo",
    "kia",
    "kml",
    "kmz",
    "kne",
    "knp",
    "kon",
    "kpr",
    "kpt",
    "kpxx",
    "ksh",
    "ksp",
    "ktr",
    "ktx",
    "ktz",
    "kwd",
    "kwt",
    "lasxml",
    "latex",
    "lbd",
    "lbe",
    "les",
    "less",
    "lgr",
    "lha",
    "lhs",
    "lib",
    "link66",
    "lisp",
    "list",
    "list3820",
    "listafp",
    "litcoffee",
    "lnk",
    "log",
    "lostxml",
    "lrf",
    "lrm",
    "ls",
    "lsp",
    "ltf",
    "lua",
    "luac",
    "lvp",
    "lwp",
    "lz",
    "lzh",
    "lzma",
    "lzo",
    "m",
    "m13",
    "m14",
    "m1v",
    "m21",
    "m2a",
    "m2v",
    "m3a",
    "m3u",
    "m3u8",
    "m4",
    "m4a",
    "m4p",
    "m4u",
    "m4v",
    "ma",
    "mads",
    "maei",
    "mag",
    "mak",
    "maker",
    "man",
    "manifest",
    "map",
    "mar",
    "markdown",
    "master",
    "mathml",
    "mb",
    "mbk",
    "mbox",
    "mc1",
    "mcd",
    "mcurl",
    "md",
    "mdb",
    "mdi",
    "mdown",
    "mdwn",
    "mdx",
    "me",
    "mesh",
    "meta4",
    "metadata",
    "metalink",
    "mets",
    "mfm",
    "mft",
    "mgp",
    "mgz",
    "mht",
    "mhtml",
    "mid",
    "midi",
    "mie",
    "mif",
    "mime",
    "mj2",
    "mjp2",
    "mjs",
    "mk",
    "mk3d",
    "mka",
    "mkd",
    "mkdn",
    "mkdown",
    "mks",
    "mkv",
    "ml",
    "mli",
    "mlp",
    "mm",
    "mmd",
    "mmf",
    "mml",
    "mmr",
    "mng",
    "mny",
    "mobi",
    "mods",
    "mov",
    "movie",
    "mp2",
    "mp21",
    "mp2a",
    "mp3",
    "mp4",
    "mp4a",
    "mp4s",
    "mp4v",
    "mpc",
    "mpd",
    "mpe",
    "mpeg",
    "mpg",
    "mpg4",
    "mpga",
    "mpkg",
    "mpm",
    "mpn",
    "mpp",
    "mpt",
    "mpy",
    "mqy",
    "mrc",
    "mrcx",
    "ms",
    "mscml",
    "mseed",
    "mseq",
    "msf",
    "msg",
    "msh",
    "msi",
    "msl",
    "msm",
    "msp",
    "msty",
    "mtl",
    "mts",
    "mus",
    "musd",
    "musicxml",
    "mvb",
    "mwf",
    "mxf",
    "mxl",
    "mxmf",
    "mxml",
    "mxs",
    "mxu",
    "n3",
    "nb",
    "nbp",
    "nc",
    "ncx",
    "nef",
    "nfm",
    "nfo",
    "n-gage",
    "ngdat",
    "nitf",
    "nlu",
    "nml",
    "nnd",
    "nns",
    "nnw",
    "noon",
    "npmignore",
    "npmrc",
    "npx",
    "nq",
    "nsc",
    "nsf",
    "nt",
    "ntf",
    "numbers",
    "nupkg",
    "nuspec",
    "nvmrc",
    "nzb",
    "o",
    "oa2",
    "oa3",
    "oas",
    "obd",
    "obgx",
    "obj",
    "oda",
    "odb",
    "odc",
    "odf",
    "odft",
    "odg",
    "odi",
    "odm",
    "odp",
    "ods",
    "odt",
    "oga",
    "ogex",
    "ogg",
    "ogv",
    "ogx",
    "omdoc",
    "onepkg",
    "onetmp",
    "onetoc",
    "onetoc2",
    "opf",
    "opml",
    "oprc",
    "ops",
    "org",
    "osf",
    "osfpvg",
    "osm",
    "otc",
    "otf",
    "otg",
    "oth",
    "oti",
    "otp",
    "ots",
    "ott",
    "ova",
    "ovf",
    "owl",
    "oxps",
    "oxt",
    "p",
    "p10",
    "p12",
    "p7b",
    "p7c",
    "p7m",
    "p7r",
    "p7s",
    "p8",
    "pac",
    "pages",
    "pas",
    "pasm",
    "patch",
    "paw",
    "pbd",
    "pbm",
    "pbxproj",
    "pcap",
    "pcf",
    "pch",
    "pcl",
    "pclxl",
    "pct",
    "pcurl",
    "pcx",
    "pdb",
    "pde",
    "pdf",
    "pea",
    "pem",
    "pfa",
    "pfb",
    "pfm",
    "pfr",
    "pfx",
    "pg",
    "pgm",
    "pgn",
    "pgp",
    "php",
    "php3",
    "php4",
    "php5",
    "phpt",
    "phtml",
    "pic",
    "pir",
    "pkg",
    "pki",
    "pkipath",
    "pkpass",
    "pl",
    "plb",
    "plc",
    "plf",
    "pls",
    "pm",
    "pmc",
    "pml",
    "png",
    "pnm",
    "pod",
    "portpkg",
    "pot",
    "potm",
    "potx",
    "ppa",
    "ppam",
    "ppd",
    "ppm",
    "pps",
    "ppsm",
    "ppsx",
    "ppt",
    "pptm",
    "pptx",
    "pqa",
    "prc",
    "pre",
    "prettierrc",
    "prf",
    "properties",
    "props",
    "provx",
    "ps",
    "psb",
    "psd",
    "psf",
    "pskcxml",
    "pt",
    "pti",
    "ptid",
    "pub",
    "pug",
    "purs",
    "pvb",
    "pwn",
    "py",
    "pya",
    "pyc",
    "pyo",
    "pyv",
    "pyx",
    "qam",
    "qbo",
    "qfx",
    "qps",
    "qt",
    "qwd",
    "qwt",
    "qxb",
    "qxd",
    "qxl",
    "qxt",
    "r",
    "ra",
    "rake",
    "ram",
    "raml",
    "rapd",
    "rar",
    "ras",
    "raw",
    "rb",
    "rbw",
    "rc",
    "rcprofile",
    "rdf",
    "rdoc",
    "rdoc_options",
    "rdz",
    "relo",
    "rep",
    "res",
    "resources",
    "resx",
    "rexx",
    "rgb",
    "rhtml",
    "rif",
    "rip",
    "ris",
    "rjs",
    "rl",
    "rlc",
    "rld",
    "rlib",
    "rm",
    "rmf",
    "rmi",
    "rmp",
    "rms",
    "rmvb",
    "rnc",
    "rng",
    "roa",
    "roff",
    "ron",
    "rp9",
    "rpm",
    "rpss",
    "rpst",
    "rq",
    "rs",
    "rsat",
    "rsd",
    "rsheet",
    "rss",
    "rst",
    "rtf",
    "rtx",
    "run",
    "rusd",
    "rvmrc",
    "rxml",
    "rz",
    "s",
    "s3m",
    "s7z",
    "saf",
    "sass",
    "sbml",
    "sc",
    "scala",
    "scd",
    "scm",
    "scpt",
    "scq",
    "scs",
    "scss",
    "scurl",
    "sda",
    "sdc",
    "sdd",
    "sdkd",
    "sdkm",
    "sdp",
    "sdw",
    "sea",
    "see",
    "seed",
    "seestyle",
    "sema",
    "semd",
    "semf",
    "senmlx",
    "sensmlx",
    "ser",
    "setpay",
    "setreg",
    "sfd-hdstx",
    "sfs",
    "sfv",
    "sgi",
    "sgl",
    "sgm",
    "sgml",
    "sh",
    "shar",
    "shex",
    "shf",
    "shtml",
    "sid",
    "sieve",
    "sig",
    "sil",
    "silo",
    "sis",
    "sisx",
    "sit",
    "sitx",
    "siv",
    "skd",
    "sketch",
    "skm",
    "skp",
    "skt",
    "sldm",
    "sldx",
    "slim",
    "slk",
    "slm",
    "sln",
    "sls",
    "slt",
    "sm",
    "smf",
    "smi",
    "smil",
    "smv",
    "smzip",
    "snd",
    "snf",
    "snk",
    "so",
    "spc",
    "spec",
    "spf",
    "spl",
    "spot",
    "spp",
    "spq",
    "spx",
    "sql",
    "sqlite",
    "sqlproj",
    "src",
    "srt",
    "sru",
    "srx",
    "ss",
    "ssdl",
    "sse",
    "ssf",
    "ssml",
    "sss",
    "st",
    "stc",
    "std",
    "stf",
    "sti",
    "stk",
    "stl",
    "str",
    "strings",
    "stw",
    "sty",
    "styl",
    "stylus",
    "sub",
    "sublime-build",
    "sublime-commands",
    "sublime-completions",
    "sublime-keymap",
    "sublime-macro",
    "sublime-menu",
    "sublime-project",
    "sublime-settings",
    "sublime-workspace",
    "suo",
    "sus",
    "susp",
    "sv",
    "sv4cpio",
    "sv4crc",
    "svc",
    "svd",
    "svg",
    "svgz",
    "swa",
    "swf",
    "swi",
    "swidtag",
    "swift",
    "sxc",
    "sxd",
    "sxg",
    "sxi",
    "sxm",
    "sxw",
    "t",
    "t3",
    "t38",
    "taglet",
    "tao",
    "tap",
    "tar",
    "tbz",
    "tbz2",
    "tcap",
    "tcl",
    "tcsh",
    "teacher",
    "tei",
    "teicorpus",
    "terminal",
    "tex",
    "texi",
    "texinfo",
    "text",
    "textile",
    "tfi",
    "tfm",
    "tfx",
    "tg",
    "tga",
    "tgz",
    "thmx",
    "tif",
    "tiff",
    "tk",
    "tlz",
    "tmLanguage",
    "tmo",
    "tmpl",
    "tmTheme",
    "toml",
    "torrent",
    "tpl",
    "tpt",
    "tr",
    "tra",
    "trm",
    "ts",
    "tsd",
    "tsv",
    "tsx",
    "tt",
    "tt2",
    "ttc",
    "ttf",
    "ttl",
    "ttml",
    "twd",
    "twds",
    "twig",
    "txd",
    "txf",
    "txt",
    "txz",
    "u32",
    "u8dsn",
    "u8hdr",
    "u8mdn",
    "u8msg",
    "udeb",
    "udf",
    "ufd",
    "ufdl",
    "ulx",
    "umj",
    "unityweb",
    "uoml",
    "uri",
    "uris",
    "urls",
    "usdz",
    "ustar",
    "utz",
    "uu",
    "uva",
    "uvd",
    "uvf",
    "uvg",
    "uvh",
    "uvi",
    "uvm",
    "uvp",
    "uvs",
    "uvt",
    "uvu",
    "uvv",
    "uvva",
    "uvvd",
    "uvvf",
    "uvvg",
    "uvvh",
    "uvvi",
    "uvvm",
    "uvvp",
    "uvvs",
    "uvvt",
    "uvvu",
    "uvvv",
    "uvvx",
    "uvvz",
    "uvx",
    "uvz",
    "v",
    "vb",
    "vbe",
    "vbox",
    "vbox-extpack",
    "vbproj",
    "vbs",
    "vcard",
    "vcd",
    "vcf",
    "vcg",
    "vcproj",
    "vcs",
    "vcx",
    "vcxproj",
    "vdi",
    "vh",
    "vhd",
    "vhdl",
    "vim",
    "viminfo",
    "vimrc",
    "vis",
    "viv",
    "vm",
    "vmdk",
    "vob",
    "vor",
    "vox",
    "vrml",
    "vsd",
    "vsf",
    "vss",
    "vst",
    "vsw",
    "vtf",
    "vtt",
    "vtu",
    "vue",
    "vxml",
    "w3d",
    "wad",
    "wadl",
    "war",
    "wasm",
    "wav",
    "wax",
    "wbmp",
    "wbs",
    "wbxml",
    "wcm",
    "wdb",
    "wdp",
    "weba",
    "webapp",
    "webm",
    "webmanifest",
    "webp",
    "wg",
    "wgt",
    "whl",
    "wim",
    "wks",
    "wm",
    "wma",
    "wmd",
    "wmf",
    "wml",
    "wmlc",
    "wmls",
    "wmlsc",
    "wmv",
    "wmx",
    "wmz",
    "woff",
    "woff2",
    "wpd",
    "wpl",
    "wps",
    "wqd",
    "wri",
    "wrl",
    "wrm",
    "wsc",
    "wsdl",
    "wspolicy",
    "wtb",
    "wvx",
    "x32",
    "x3d",
    "x3db",
    "x3dbz",
    "x3dv",
    "x3dvz",
    "x3dz",
    "xaml",
    "xap",
    "xar",
    "xav",
    "x_b",
    "xbap",
    "xbd",
    "xbm",
    "xca",
    "xcs",
    "xdf",
    "xdm",
    "xdp",
    "xdssc",
    "xdw",
    "xel",
    "xenc",
    "xer",
    "xfdf",
    "xfdl",
    "xht",
    "xhtml",
    "xhvml",
    "xif",
    "xla",
    "xlam",
    "xlc",
    "xlf",
    "xlm",
    "xls",
    "xlsb",
    "xlsm",
    "xlsx",
    "xlt",
    "xltm",
    "xltx",
    "xlw",
    "xm",
    "xmind",
    "xml",
    "xns",
    "xo",
    "xop",
    "x-php",
    "xpi",
    "xpl",
    "xpm",
    "xpr",
    "xps",
    "xpw",
    "xpx",
    "xs",
    "xsd",
    "xsl",
    "xslt",
    "xsm",
    "xspf",
    "x_t",
    "xul",
    "xvm",
    "xvml",
    "xwd",
    "xyz",
    "xz",
    "y",
    "yaml",
    "yang",
    "yin",
    "yml",
    "ymp",
    "z",
    "z1",
    "z2",
    "z3",
    "z4",
    "z5",
    "z6",
    "z7",
    "z8",
    "zaz",
    "zip",
    "zipx",
    "zir",
    "zirz",
    "zmm",
    "zsh",
    "zshrc"
};

#endif /* FINGER_CONFIGS_HPP */
