name: "Build docker image"

on:
  push:
    branches: [main, dev, d/*]
  pull_request:
    branches: [main, dev, d/*]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:webgoat"
          push: false
          tags: fingerlib/webgoat:latest
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:dvwa"
          push: false
          tags: fingerlib/dvwa:latest
